[CmdletBinding()]
param(
    [string] $QtRoot = $env:QT_ROOT_DIR,

    [ValidateSet('Debug', 'Release')]
    [string] $Configuration = 'Release',

    [int] $Parallel = [Environment]::ProcessorCount,

    [string] $Generator,

    [string] $Architecture = 'x64',

    [string] $Toolset = 'host=x64'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repositoryRoot = Split-Path $PSScriptRoot -Parent
$workRoot = Join-Path $repositoryRoot ".work\$Configuration"
$workRoot = [System.IO.Path]::GetFullPath($workRoot)

if (-not $QtRoot) {
    throw 'Specify -QtRoot or set QT_ROOT_DIR.'
}
$QtRoot = [System.IO.Path]::GetFullPath($QtRoot)
$qtCMake = Join-Path $QtRoot 'bin\qt-cmake-private.bat'
if (-not (Test-Path -LiteralPath $qtCMake)) {
    throw "Qt private module build helper was not found: $qtCMake"
}
$qtPaths = @('qtpaths6.exe', 'qtpaths.exe') |
    ForEach-Object { Join-Path $QtRoot "bin\$_" } |
    Where-Object { Test-Path -LiteralPath $_ } |
    Select-Object -First 1
if (-not $qtPaths) {
    throw "qtpaths was not found under $QtRoot\bin."
}
$qtVersion = (& $qtPaths --qt-version).Trim()
if ($LASTEXITCODE -ne 0 -or $qtVersion -notmatch '^\d+\.\d+\.\d+$') {
    throw "Unable to determine the Qt version from $qtPaths."
}
Write-Host "Building QtScript package version $qtVersion for Qt at $QtRoot"
if (-not (Get-Command cmake.exe -ErrorAction SilentlyContinue)) {
    throw 'cmake.exe was not found on PATH.'
}

$sourceDir = Join-Path $workRoot 'src'
$buildDir = Join-Path $workRoot 'build'
$smokeBuildDir = Join-Path $workRoot 'smoke-build'

& (Join-Path $PSScriptRoot 'apply-patches.ps1') -SourceDir $sourceDir

# CMake auto-detects the newest installed Visual Studio when no -Generator
# is given; -A/-T only apply to Visual Studio generators.
$generatorArgs = @()
if ($Generator) {
    $generatorArgs += @('-G', $Generator)
}
if (-not $Generator -or $Generator -like 'Visual Studio*') {
    if ($Architecture) { $generatorArgs += @('-A', $Architecture) }
    if ($Toolset) { $generatorArgs += @('-T', $Toolset) }
}

$installRoot = $QtRoot.Replace('\', '/')
& $qtCMake @(
    '-S', $sourceDir,
    '-B', $buildDir,
    @generatorArgs,
    "-DCMAKE_INSTALL_PREFIX=$installRoot",
    "-DQT_REPO_MODULE_VERSION=$qtVersion",
    '-DQT_BUILD_TESTS=OFF',
    '-DQT_BUILD_EXAMPLES=OFF'
)
if ($LASTEXITCODE -ne 0) { throw 'QtScript configuration failed.' }

$configurationLine = Get-Content -LiteralPath (Join-Path $buildDir 'CMakeCache.txt') |
    Where-Object { $_ -match '^CMAKE_CONFIGURATION_TYPES:[^=]+=' } |
    Select-Object -First 1
if (-not $configurationLine) {
    throw 'Unable to determine the configurations generated by CMake.'
}
$availableConfigurations = @($configurationLine.Split('=', 2)[1].Split(';'))
$effectiveConfiguration = $Configuration
if ($Configuration -eq 'Release' -and
    $availableConfigurations -notcontains 'Release' -and
    $availableConfigurations -contains 'RelWithDebInfo') {
    $effectiveConfiguration = 'RelWithDebInfo'
}
if ($availableConfigurations -notcontains $effectiveConfiguration) {
    throw "Configuration $Configuration is unavailable. Generated: $($availableConfigurations -join ', ')"
}
Write-Host "Using CMake configuration $effectiveConfiguration for requested $Configuration build"

& cmake --build $buildDir --config $effectiveConfiguration --parallel $Parallel
if ($LASTEXITCODE -ne 0) { throw 'QtScript build failed.' }

& cmake --install $buildDir --config $effectiveConfiguration
if ($LASTEXITCODE -ne 0) { throw 'QtScript installation failed.' }

$metadataFiles = @()
foreach ($root in @(
    (Join-Path $QtRoot 'lib\cmake\Qt6Script'),
    (Join-Path $QtRoot 'mkspecs\modules\qt_lib_script.pri')
)) {
    if (Test-Path -LiteralPath $root) {
        $metadataFiles += @(Get-ChildItem -LiteralPath $root -Recurse -File |
            Where-Object { $_.Extension -in '.cmake', '.pri', '.prl' })
    }
}
$forbiddenPaths = @(
    $sourceDir,
    $sourceDir.Replace('\', '/'),
    $buildDir,
    $buildDir.Replace('\', '/')
) | Select-Object -Unique
$metadataLeaks = @()
if ($metadataFiles.Count -ne 0) {
    $metadataLeaks = @(Select-String `
        -LiteralPath $metadataFiles.FullName `
        -SimpleMatch `
        -Pattern $forbiddenPaths)
}
if ($metadataLeaks.Count -ne 0) {
    $locations = $metadataLeaks |
        ForEach-Object { "$($_.Path):$($_.LineNumber)" } |
        Sort-Object -Unique
    throw "Installed metadata contains source/build paths:`n$($locations -join "`n")"
}

& cmake @(
    '-S', (Join-Path $repositoryRoot 'tests\smoke'),
    '-B', $smokeBuildDir,
    @generatorArgs,
    "-DCMAKE_PREFIX_PATH=$installRoot"
)
if ($LASTEXITCODE -ne 0) { throw 'Smoke-test configuration failed.' }

& cmake --build $smokeBuildDir --config $effectiveConfiguration --parallel $Parallel
if ($LASTEXITCODE -ne 0) { throw 'Smoke-test build failed.' }

$originalPath = $env:PATH
try {
    $env:PATH = "$(Join-Path $QtRoot 'bin');$originalPath"
    & ctest --test-dir $smokeBuildDir -C $effectiveConfiguration --output-on-failure
    if ($LASTEXITCODE -ne 0) { throw 'Smoke test failed.' }
} finally {
    $env:PATH = $originalPath
}

Write-Host "QtScript $Configuration installed into $QtRoot"
