[CmdletBinding()]
param(
    [string] $QtRoot = $env:QT_ROOT_DIR,

    [ValidateSet('Debug', 'Release')]
    [string] $Configuration = 'Release',

    [string] $WorkRoot,

    [int] $Parallel = [Environment]::ProcessorCount,

    [switch] $UseQuickJS
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repositoryRoot = Split-Path $PSScriptRoot -Parent
if (-not $WorkRoot) {
    $WorkRoot = Join-Path $repositoryRoot ".work\$Configuration"
}
$WorkRoot = [System.IO.Path]::GetFullPath($WorkRoot)

if (-not $QtRoot) {
    throw 'Specify -QtRoot or set QT_ROOT_DIR.'
}
$QtRoot = [System.IO.Path]::GetFullPath($QtRoot)
$qtCMake = Join-Path $QtRoot 'bin\qt-cmake-private.bat'
if (-not (Test-Path -LiteralPath $qtCMake)) {
    throw "Qt private module build helper was not found: $qtCMake"
}
$qtPaths = @('qtpaths6.exe', 'qtpaths.exe') |
    ForEach-Object { Join-Path $QtRoot "bin\$_" } |
    Where-Object { Test-Path -LiteralPath $_ } |
    Select-Object -First 1
if (-not $qtPaths) {
    throw "qtpaths was not found under $QtRoot\bin."
}
$qtVersion = (& $qtPaths --qt-version).Trim()
if ($LASTEXITCODE -ne 0 -or $qtVersion -notmatch '^\d+\.\d+\.\d+$') {
    throw "Unable to determine the Qt version from $qtPaths."
}
Write-Host "Building QtScript package version $qtVersion for Qt at $QtRoot"
if (-not (Get-Command cmake.exe -ErrorAction SilentlyContinue)) {
    throw 'cmake.exe was not found on PATH.'
}

$sourceDir = Join-Path $WorkRoot 'src'
$buildDir = Join-Path $WorkRoot 'build'
$installDir = Join-Path $WorkRoot 'install'
$smokeBuildDir = Join-Path $WorkRoot 'smoke-build'

# Clean any dirty overrides from previous builds to allow apply-patches to run cleanly
if (Test-Path -LiteralPath (Join-Path $sourceDir ".git")) {
    Write-Host "Resetting dirty files in build source directory..."
    & git -C $sourceDir reset --hard
    & git -C $sourceDir clean -fd
}

& (Join-Path $PSScriptRoot 'apply-patches.ps1') -SourceDir $sourceDir

if ($UseQuickJS) {
    Write-Host "Applying QuickJS migration overrides..."
    $scriptDir = Join-Path $sourceDir "src\script"
    $thirdpartyDir = Join-Path $sourceDir "src\3rdparty\quickjs"

    New-Item -ItemType Directory -Path $thirdpartyDir -Force | Out-Null

    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\3rdparty\quickjs\*") -Destination $thirdpartyDir -Force
    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\qscriptengine.h") -Destination (Join-Path $scriptDir "api") -Force
    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\qscriptengine.cpp") -Destination (Join-Path $scriptDir "api") -Force
    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\qscriptvalue.h") -Destination (Join-Path $scriptDir "api") -Force
    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\qscriptvalue_p.h") -Destination (Join-Path $scriptDir "api") -Force
    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\qscriptvalue.cpp") -Destination (Join-Path $scriptDir "api") -Force
    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\qregexp.h") -Destination (Join-Path $scriptDir "api") -Force
    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\qregexp.cpp") -Destination (Join-Path $scriptDir "api") -Force
    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\qobject_bridge.cpp") -Destination (Join-Path $scriptDir "bridge") -Force
    Copy-Item -Path (Join-Path $repositoryRoot "quickjs_migration\CMakeLists.txt") -Destination $scriptDir -Force
}

$installCMakePath = $installDir.Replace('\', '/')
& $qtCMake @(
    '-S', $sourceDir,
    '-B', $buildDir,
    '-G', 'Visual Studio 17 2022',
    '-A', 'x64',
    '-T', 'host=x64',
    "-DCMAKE_INSTALL_PREFIX=$installCMakePath",
    "-DQT_REPO_MODULE_VERSION=$qtVersion",
    '-DQT_BUILD_TESTS=OFF',
    '-DQT_BUILD_EXAMPLES=OFF'
)
if ($LASTEXITCODE -ne 0) { throw 'QtScript configuration failed.' }

$configurationLine = Get-Content -LiteralPath (Join-Path $buildDir 'CMakeCache.txt') |
    Where-Object { $_ -match '^CMAKE_CONFIGURATION_TYPES:[^=]+=' } |
    Select-Object -First 1
if (-not $configurationLine) {
    throw 'Unable to determine the configurations generated by CMake.'
}
$availableConfigurations = @($configurationLine.Split('=', 2)[1].Split(';'))
$effectiveConfiguration = $Configuration
if ($Configuration -eq 'Release' -and
    $availableConfigurations -notcontains 'Release' -and
    $availableConfigurations -contains 'RelWithDebInfo') {
    $effectiveConfiguration = 'RelWithDebInfo'
}
if ($availableConfigurations -notcontains $effectiveConfiguration) {
    throw "Configuration $Configuration is unavailable. Generated: $($availableConfigurations -join ', ')"
}
Write-Host "Using CMake configuration $effectiveConfiguration for requested $Configuration build"

& cmake --build $buildDir --config $effectiveConfiguration --parallel $Parallel
if ($LASTEXITCODE -ne 0) { throw 'QtScript build failed.' }

& cmake --install $buildDir --config $effectiveConfiguration
if ($LASTEXITCODE -ne 0) { throw 'QtScript installation failed.' }

if (-not $UseQuickJS) {
    $metadataFiles = @(Get-ChildItem -LiteralPath $installDir -Recurse -File |
        Where-Object { $_.Extension -in '.cmake', '.pri', '.prl' })
    $forbiddenPaths = @(
        $sourceDir,
        $sourceDir.Replace('\', '/'),
        $buildDir,
        $buildDir.Replace('\', '/')
    ) | Select-Object -Unique
    $metadataLeaks = @()
    if ($metadataFiles.Count -ne 0) {
        $metadataLeaks = @(Select-String `
            -LiteralPath $metadataFiles.FullName `
            -SimpleMatch `
            -Pattern $forbiddenPaths)
    }
    if ($metadataLeaks.Count -ne 0) {
        $locations = $metadataLeaks |
            ForEach-Object { "$($_.Path):$($_.LineNumber)" } |
            Sort-Object -Unique
        throw "Installed metadata contains source/build paths:`n$($locations -join "`n")"
    }
}

$prefixPath = "$installCMakePath;$($QtRoot.Replace('\', '/'))"
& cmake @(
    '-S', (Join-Path $repositoryRoot 'tests\smoke'),
    '-B', $smokeBuildDir,
    '-G', 'Visual Studio 17 2022',
    '-A', 'x64',
    '-T', 'host=x64',
    "-DCMAKE_PREFIX_PATH=$prefixPath",
    "-DQT_ADDITIONAL_PACKAGES_PREFIX_PATH=$installCMakePath"
)
if ($LASTEXITCODE -ne 0) { throw 'Smoke-test configuration failed.' }

& cmake --build $smokeBuildDir --config $effectiveConfiguration --parallel $Parallel
if ($LASTEXITCODE -ne 0) { throw 'Smoke-test build failed.' }

$originalPath = $env:PATH
try {
    $env:PATH = "$(Join-Path $installDir 'bin');$(Join-Path $QtRoot 'bin');$originalPath"
    & ctest --test-dir $smokeBuildDir -C $effectiveConfiguration --output-on-failure
    if ($LASTEXITCODE -ne 0) { throw 'Smoke test failed.' }
} finally {
    $env:PATH = $originalPath
}

Write-Host "QtScript $Configuration install ($effectiveConfiguration): $installDir"
