if(NOT DEFINED QT_REPO_MODULE_VERSION)
    set(QT_REPO_MODULE_VERSION "6.8.3")
endif()
set(QT_REPO_MODULE_PRERELEASE_VERSION_SEGMENT "")

list(APPEND QT_EXTRA_INTERNAL_TARGET_DEFINES "QT_NO_FOREACH=1")
list(APPEND QT_EXTRA_INTERNAL_TARGET_DEFINES "QT_NO_JAVA_STYLE_ITERATORS=1")